Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ${env:AWS_AVAILABILITY_ZONE}
      CreditSpecification:
        CPUCredits: standard
      DisableApiTermination: false
      EbsOptimized: false
      IamInstanceProfile: ${env:AWS_IAM_INSTANCE_PROFILE}
      ImageId: ${env:AWS_IMAGE_ID}
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: ${env:AWS_INSTANCE_TYPE}
      KeyName: ${env:AWS_KEY_PAIR}
      Monitoring: false
      SecurityGroupIds:
        - ${env:AWS_SECURITY_GROUP}
      Tags:
        - Key: Name
          Value: ${env:APP_NAME}
