service: ${env:SERVICE_ID}

useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_REGION}
  stage: prod

resources:
  - ${file(src/resources/EIP.yml)}
  - ${file(src/resources/instance.yml)}
  - ${file(src/resources/codeDeploy.yml)}
